name: longtake
description: Flutter long-time photo shooting.
version: 0.9.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  camera: ^0.9.4+14
  path_provider: ^2.0.8
  gallery_saver: ^2.3.2

  permission_handler: ^9.0.2
  photo_manager: ^1.3.10
  photo_gallery: ^1.1.1
  intl: ^0.17.0
  disk_space: ^0.2.1
  shared_preferences: ^2.0.13

  battery_plus: ^2.1.1

  image: ^3.1.3
  flutter_native_splash: ^1.3.1
  hooks_riverpod: ^1.0.3
  video_thumbnail: ^0.5.0
  native_device_orientation: ^1.0.0
  flutter_video_info: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/test.png
